# Generated by Django 2.1.5 on 2019-02-07 10:51

from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '__first__'),
        ('project', '0001_initial'),
        ('student', '0002_student_state'),
        ('asset', '0002_auto_20190207_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_Curricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modification date and time')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modification date and time')),
                ('title', models.CharField(max_length=30)),
                ('details', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modification date and time')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('ABU', 'Abuja'), ('ABI', 'Abia'), ('ADA', 'Adamawa'), ('AKW', 'Akwa Ibom'), ('ANA', 'Anambra'), ('BAU', 'Bauchi'), ('BAY', 'Bayelsa'), ('BEN', 'Benue'), ('BOR', 'Borno'), ('CRO', 'Cross River'), ('DEL', 'Delta'), ('EBO', 'Ebonyi'), ('ENU', 'Enugu'), ('EDO', 'Edo'), ('EKI', 'Ekiti'), ('GOM', 'Gombe'), ('IMO', 'Imo'), ('JIG', 'Jigawa'), ('KAD', 'Kaduna'), ('KAN', 'Kano'), ('KAT', 'Katsina'), ('KEB', 'Kebbi'), ('KOG', 'Kogi'), ('KWA', 'Kwara'), ('LAG', 'Lagos'), ('NAS', 'Nasarawa'), ('NIG', 'Niger'), ('OGU', 'Ogun'), ('OND', 'Ondo'), ('OSU', 'Osun'), ('OYO', 'Oyo'), ('PLA', 'Plateau'), ('RIV', 'Rivers'), ('SOK', 'Sokoto'), ('TAR', 'Taraba'), ('YOB', 'Yobe'), ('ZAM', 'Zamfara')], max_length=20)),
                ('date_of_creation', models.DateField(blank=True, null=True, validators=[utils.models.no_future])),
                ('asset', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Asset')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('teacher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
        migrations.AddField(
            model_name='extra_curricular',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
