# Generated by Django 2.1.5 on 2019-02-07 11:19

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='date_of_creation',
            field=models.DateField(null=True, validators=[utils.models.no_future]),
        ),
    ]
