# Generated by Django 2.1.5 on 2019-02-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modification date and time')),
                ('name', models.CharField(max_length=200)),
                ('date_commissioned', models.DateField()),
                ('details', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('ABU', 'Abuja'), ('ABI', 'Abia'), ('ADA', 'Adamawa'), ('AKW', 'Akwa Ibom'), ('ANA', 'Anambra'), ('BAU', 'Bauchi'), ('BAY', 'Bayelsa'), ('BEN', 'Benue'), ('BOR', 'Borno'), ('CRO', 'Cross River'), ('DEL', 'Delta'), ('EBO', 'Ebonyi'), ('ENU', 'Enugu'), ('EDO', 'Edo'), ('EKI', 'Ekiti'), ('GOM', 'Gombe'), ('IMO', 'Imo'), ('JIG', 'Jigawa'), ('KAD', 'Kaduna'), ('KAN', 'Kano'), ('KAT', 'Katsina'), ('KEB', 'Kebbi'), ('KOG', 'Kogi'), ('KWA', 'Kwara'), ('LAG', 'Lagos'), ('NAS', 'Nasarawa'), ('NIG', 'Niger'), ('OGU', 'Ogun'), ('OND', 'Ondo'), ('OSU', 'Osun'), ('OYO', 'Oyo'), ('PLA', 'Plateau'), ('RIV', 'Rivers'), ('SOK', 'Sokoto'), ('TAR', 'Taraba'), ('YOB', 'Yobe'), ('ZAM', 'Zamfara')], max_length=20, null=True)),
                ('value', models.IntegerField()),
                ('expired_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
