# Generated by Django 2.1.4 on 2019-02-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('ABU', 'Abuja'), ('ABI', 'Abia'), ('ADA', 'Adamawa'), ('AKW', 'Akwa Ibom'), ('ANA', 'Anambra'), ('BAU', 'Bauchi'), ('BAY', 'Bayelsa'), ('BEN', 'Benue'), ('BOR', 'Borno'), ('CRO', 'Cross River'), ('DEL', 'Delta'), ('EBO', 'Ebonyi'), ('ENU', 'Enugu'), ('EDO', 'Edo'), ('EKI', 'Ekiti'), ('GOM', 'Gombe'), ('IMO', 'Imo'), ('JIG', 'Jigawa'), ('KAD', 'Kaduna'), ('KAN', 'Kano'), ('KAT', 'Katsina'), ('KEB', 'Kebbi'), ('KOG', 'Kogi'), ('KWA', 'Kwara'), ('LAG', 'Lagos'), ('NAS', 'Nasarawa'), ('NIG', 'Niger'), ('OGU', 'Ogun'), ('OND', 'Ondo'), ('OSU', 'Osun'), ('OYO', 'Oyo'), ('PLA', 'Plateau'), ('RIV', 'Rivers'), ('SOK', 'Sokoto'), ('TAR', 'Taraba'), ('YOB', 'Yobe'), ('ZAM', 'Zamfara')], max_length=20, null=True),
        ),
    ]
